"""Initial migration for TestingData database

Revision ID: 17c334c11115
Revises: d35bb00ed5cb
Create Date: 2024-06-12 11:04:53.587154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c334c11115'
down_revision = 'd35bb00ed5cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
