"""Created the tables again

Revision ID: ba9d511efa86
Revises: 
Create Date: 2024-07-09 13:57:45.764452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9d511efa86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumers',
    sa.Column('Consumer_ID', sa.String(length=100), nullable=False),
    sa.Column('City', sa.String(length=100), nullable=True),
    sa.Column('State', sa.String(length=100), nullable=True),
    sa.Column('Country', sa.String(length=100), nullable=True),
    sa.Column('Latitude', sa.Float(), nullable=True),
    sa.Column('Longitude', sa.Float(), nullable=True),
    sa.Column('Smoker', sa.String(length=50), nullable=True),
    sa.Column('Drink_Level', sa.String(length=50), nullable=True),
    sa.Column('Transportation_Method', sa.String(length=100), nullable=True),
    sa.Column('Marital_Status', sa.String(length=100), nullable=True),
    sa.Column('Children', sa.String(length=100), nullable=True),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('Occupation', sa.String(length=100), nullable=True),
    sa.Column('Budget', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('Consumer_ID')
    )
    op.create_table('restaurants',
    sa.Column('Restaurant_ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=True),
    sa.Column('City', sa.String(length=100), nullable=True),
    sa.Column('State', sa.String(length=100), nullable=True),
    sa.Column('Country', sa.String(length=100), nullable=True),
    sa.Column('Zip_Code', sa.String(length=20), nullable=True),
    sa.Column('Latitude', sa.Float(), nullable=True),
    sa.Column('Longitude', sa.Float(), nullable=True),
    sa.Column('Alcohol_Service', sa.String(length=50), nullable=True),
    sa.Column('Smoking_Allowed', sa.String(length=50), nullable=True),
    sa.Column('Price', sa.String(length=50), nullable=True),
    sa.Column('Franchise', sa.String(length=50), nullable=True),
    sa.Column('Area', sa.String(length=100), nullable=True),
    sa.Column('Parking', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('Restaurant_ID')
    )
    op.create_table('consumer_preferences',
    sa.Column('Consumer_ID', sa.String(length=100), nullable=False),
    sa.Column('Preferred_Cuisine', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['Consumer_ID'], ['consumers.Consumer_ID'], ),
    sa.PrimaryKeyConstraint('Consumer_ID', 'Preferred_Cuisine')
    )
    op.create_table('ratings',
    sa.Column('Consumer_ID', sa.String(length=100), nullable=False),
    sa.Column('Restaurant_ID', sa.Integer(), nullable=False),
    sa.Column('Overall_Rating', sa.Integer(), nullable=True),
    sa.Column('Food_Rating', sa.Integer(), nullable=True),
    sa.Column('Service_Rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Consumer_ID'], ['consumers.Consumer_ID'], ),
    sa.ForeignKeyConstraint(['Restaurant_ID'], ['restaurants.Restaurant_ID'], ),
    sa.PrimaryKeyConstraint('Consumer_ID', 'Restaurant_ID')
    )
    op.create_table('restaurant_cuisines',
    sa.Column('Restaurant_ID', sa.Integer(), nullable=False),
    sa.Column('Cuisine', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['Restaurant_ID'], ['restaurants.Restaurant_ID'], ),
    sa.PrimaryKeyConstraint('Restaurant_ID', 'Cuisine')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant_cuisines')
    op.drop_table('ratings')
    op.drop_table('consumer_preferences')
    op.drop_table('restaurants')
    op.drop_table('consumers')
    # ### end Alembic commands ###
