"""empty message

Revision ID: e3cbad6a7020
Revises: ba9d511efa86
Create Date: 2024-07-10 12:11:35.647793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3cbad6a7020'
down_revision = 'ba9d511efa86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
