"""added columns to conversation table

Revision ID: 22d92b937a34
Revises: 40fa7a564b7a
Create Date: 2024-07-03 12:40:48.528888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d92b937a34'
down_revision = '40fa7a564b7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('chartname', sa.String(length=100), nullable=True))
    op.add_column('conversation', sa.Column('labelx', sa.String(length=100), nullable=True))
    op.add_column('conversation', sa.Column('labely', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'labely')
    op.drop_column('conversation', 'labelx')
    op.drop_column('conversation', 'chartname')
    # ### end Alembic commands ###
