"""made response field in convo table bigger

Revision ID: 40fa7a564b7a
Revises: 44f66b8d8ca8
Create Date: 2024-07-02 13:53:48.739226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40fa7a564b7a'
down_revision = '44f66b8d8ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation', 'response',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation', 'response',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=False)
    # ### end Alembic commands ###
