"""Removed Xlabel and Ylabel

Revision ID: 4c1c503a8e7a
Revises: 22d92b937a34
Create Date: 2024-07-04 12:46:29.979250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c1c503a8e7a'
down_revision = '22d92b937a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'labelx')
    op.drop_column('conversation', 'labely')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('labely', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('conversation', sa.Column('labelx', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
