"""added cascading delete to chat and user, and added SECRET_KEY attribute for user class for 2fa

Revision ID: 4d2805f19dff
Revises: 4c1c503a8e7a
Create Date: 2024-07-18 16:43:16.705878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2805f19dff'
down_revision = '4c1c503a8e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_user_id_fkey', 'chat', type_='foreignkey')
    op.create_foreign_key(None, 'chat', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('user', sa.Column('secret_key', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'secret_key')
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.create_foreign_key('chat_user_id_fkey', 'chat', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
