"""Added sql_query field to conversation table

Revision ID: 6bd6f65c4c78
Revises: 970fa05f82e6
Create Date: 2024-06-20 10:56:31.746033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bd6f65c4c78'
down_revision = '970fa05f82e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('sql_query', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'sql_query')
    # ### end Alembic commands ###
