"""Added feedback table

Revision ID: 970fa05f82e6
Revises: f8995905958b
Create Date: 2024-06-19 17:18:57.475975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970fa05f82e6'
down_revision = 'f8995905958b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.String(length=10), nullable=False),
    sa.Column('feedback_comment', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
