"""Added more fields to the conversation table

Revision ID: 98f29965d542
Revises: bd7cec102e26
Create Date: 2024-06-29 14:36:52.227716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f29965d542'
down_revision = 'bd7cec102e26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('conversation', sa.Column('executable', sa.String(length=3), nullable=True))
    op.add_column('conversation', sa.Column('location', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'location')
    op.drop_column('conversation', 'executable')
    op.drop_column('conversation', 'score')
    # ### end Alembic commands ###
