"""added new columns to user table

Revision ID: a16b225d4c6a
Revises: 4d2805f19dff
Create Date: 2024-07-23 17:53:41.373123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16b225d4c6a'
down_revision = '4d2805f19dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('bio_description', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('profile_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_image')
    op.drop_column('user', 'address')
    op.drop_column('user', 'bio_description')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
